### ISSUE TITLE
error while train interactive.py

### ISSUE THREAD

**Issue by carlos12silva94** [peterldowns/clickbait-classifier#4]
after running:
$ python interactive.py

i'm getting this. How to fix?

`Loading classifier (may take time to train.)
Traceback (most recent call last):
  File "interactive.py", line 7, in <module>
    import classifier
  File "/vagrant/tese/svm/peterldowns-clickbait-classifier/classifier.py", line 21, in <module>
    import nltk
  File "/usr/local/lib/python2.7/dist-packages/nltk/__init__.py", line 117, in <module>
    from nltk.align import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/align/__init__.py", line 15, in <module>
    from nltk.align.ibm1 import IBMModel1
  File "/usr/local/lib/python2.7/dist-packages/nltk/align/ibm1.py", line 18, in <module>
    from nltk.corpus import comtrans
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/__init__.py", line 59, in <module>
    from nltk.corpus.reader.tagged import *
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/tagged.py", line 17, in <module>
    from nltk.tag import str2tuple, map_tag
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/__init__.py", line 65, in <module>
    from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/sequential.py", line 25, in <module>
    from nltk.classify.naivebayes import NaiveBayesClassifier
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/__init__.py", line 93, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/usr/local/lib/python2.7/dist-packages/nltk/classify/scikitlearn.py", line 41, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/__init__.py", line 7, in <module>
    from .dict_vectorizer import DictVectorizer
  File "/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/dict_vectorizer.py", line 14, in <module>
    from ..utils import atleast2d_or_csr, tosequence
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029)
ValueError: numpy.dtype has the wrong size, try recompiling`

**Comment by peterldowns** [comment]
Seems like it's some kind of issue with your numpy installation. Unfortunately I can't help you debug that -- I can only tell you that I've had similar errors in other projects, and had to do the nuke/reinstall/cry/nuke/reinstall/... cycle more than once.
